name: Build
on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
      solutionPath:
        required: true
        type: string
      configuration:
        required: false 
        type: string 
        default: Release
      nugetApiKey:
        required: false 
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: .\.github\workflows\shared\build
        with:
          publish: false
          solutionPath: ${{ inputs.solutionPath }}
          configuration: ${{ inputs.configuration }}
      - name: Pack 
        run: dotnet pack ${{ inputs.solutionPath }} ${{ inputs.configuration }} --output ./.artifacts
      - name: Push 
        run: dotnet nuget push ./artifacts/*nupkg --skip-duplicate --api-key ${{ inputs.NUGET_API_KEY }}  --source https://api.nuget.org/v3/index.json
