name: Build

on: [push]

env:
  solutionPath: ./Source/Seed.IO.sln
  configuration: Release


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0  
    - name: Build 
      uses: ByronMayne/Shared.Actions@2df2e851864f641de133beda5c1f0b6946be7cd9/.github/actions/build
      with: 
        publish: false 
        configuration: ${{ env.configuration }}
        solutionPath: ${{ env.solutionPath }}

