name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build 
      uses: ./.github/workflows/build.yml
      with: 
        publish: false 
        configuration: Release
        solutionPath: ./src/Seed.IO.sln

