name: Build

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build 
      uses: ./.github/actions/shared/publish
      with: 
        publish: false 
        configuration: Release
        solutionPath: ./src/Seed.IO.sln
        nugetApiKey: ${{ secrets.NUGET_API_KEY }}