name: Build

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  solutionPath: ./src/Seed.IO.sln
  configuration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
    - name: Build 
      uses: ./.github/actions/build
      with: 
        publish: false 
        configuration: ${{ env.configuration }}
        solutionPath:  ${{ env.solutionPath }}
    - name: Publish 
      uses: ./.github/actions/publish
      with: 
        publish: true 
        configuration: ${{ env.configuration }}
        solutionPath: ${{ env.solutionPath }}
        nugetApiKey: ${{ secrets.NUGET_API_KEY }}