name: Build

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
    - name: Publish 
      uses: ./.github/actions/publish
      with: 
        publish: false 
        configuration: Release
        solutionPath: ./src/Seed.IO.sln