name: Publish

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  solutionPath: ./Source/Seed.IO.sln
  configuration: Release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0  
    - name: Build 
      uses: ByronMayne/Shared.Actions/build_csharp@1.0.2
      with: 
        publish: false 
        configuration: ${{ env.configuration }}
        solutionPath:  ${{ env.solutionPath }}
    - name: Publish 
      uses: ByronMayne/Shared.Actions/publish_csharp_nuget@1.0.2
      with: 
        publish: true 
        configuration: ${{ env.configuration }}
        solutionPath: ${{ env.solutionPath }}
        nugetApiKey: ${{ secrets.NUGET_API_KEY }}