name: Publish

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  configuration: Release

jobs:
  publish:
    strategy:
      matrix:
        project:
          - Source\Seed.IO\Seed.IO.csproj
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0  
    - name: Build 
      uses: ByronMayne/Shared.Actions/build_csharp@1.0.7
      with: 
        publish: false 
        configuration: ${{ env.configuration }}
        solutionOrProjectPath: ${{ matrix.project }}
    - name: Publish 
      uses: ByronMayne/Shared.Actions/publish_csharp_nuget@1.0.7
      with: 
        publish: true 
        configuration: ${{ env.configuration }}
        solutionOrProjectPath: ${{ matrix.project }}
        nugetApiKey: ${{ secrets.NUGET_API_KEY }}